# Generated by Django 5.0.14 on 2026-08-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Dayflow HR Inc.', max_length=150)),
                ('company_email', models.EmailField(default='contact@dayflow.hr', max_length=254)),
                ('company_phone', models.CharField(default='+1 (555) 019-2834', max_length=30)),
                ('address', models.TextField(default='100 Innovation Way, Suite 400')),
                ('city', models.CharField(default='San Francisco', max_length=100)),
                ('state', models.CharField(default='CA', max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('postal_code', models.CharField(default='94105', max_length=20)),
                ('website', models.URLField(default='https://dayflow.hr')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
